[tool.poetry]
name = "imap"
version = "0.1.0"
description = "Task for Protocols"
authors = ["Vyacheslav Karpov"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
